services:
  api:
    image: bot/bot
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # enable colorized logs
    restart: always # should this be on-failure ?
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json